name: Lint Code with ESLint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $GITHUB_ENV
          source $GITHUB_ENV
          
      # Step 3: Install Dependencies with Bun
      - name: Install dependencies
        run: bun install

      # Step 4: Run ESLint
      - name: Run ESLint
        run: bun lint
